
skillMetadata:
  sections:
    - name: MAL account
      fields:
        - type: label
          label: The mal username for the user whose list you'd like to access
        - name: username
          type: text
          label: Username
          value: ""
